### ISSUE TITLE
Socket Closed

### ISSUE THREAD

**Issue by astropixel** [oznu/homebridge-syno-spk#3] opened 2017-12-08 09:46 UTC
Thanks for your great work with this package.

Everything was working as expected (no config changes), until I recently attempted to access the Terminal within a Container. I get the error 'Socket Closed'. Is there anything that might be causing this?

**Comment by oznu** [comment] 2017-12-11 05:28
I've seen this on quite a few occasions while using the DSM docker terminal feature and am fairly certain it's just a DSM bug. I've been seeing it long before I started using the oznu/homebridge Docker image.

https://forum.synology.com/enu/viewtopic.php?t=114332

If you're using a reverse proxy (like nginx) in front of DSM make sure it supports upgrading requests to a "websocket" and set a long proxy timeout.

**Comment by astropixel** [comment] 2017-12-12 07:45
Did you happen to have the fix that you used to resolve it on a DiskStation? I've seen the thread that you posted and the locations don't exist on my DiskStation?

Not using a reverse proxy.

**Comment by oznu** [comment] 2018-01-17 06:10
Closing as this is an issue with DSM not this package specifically.

**Closed by oznu** 2018-01-17 06:10 UTC

**Comment by TheAlikA** [comment] 2020-01-03 04:17
Upon some rading it seems that the problem is QuickConnect, you have to access through your Synology IP Address not through Quick Connect.

**Comment by jinnxu75** [comment] 2023-06-20 07:14
> 

yes. i am using QuickConnect, and same problem happen with another docker(icloudpd). In fact, it is ok when the image was launched first time. But when i delete the container and add it again, i have no way to use the docker terminal any more.

No solution. :(
