### ISSUE TITLE
Node.js global modules rebuild required

### ISSUE THREAD

**Issue by DaGreenX** [oznu/homebridge-syno-spk#131] opened 2023-10-30 16:08 UTC
### Current Situation

Update available.
I am updating.
the home bridge server requests a reboot.

Blank page.
Synology package stopped.
Blank page.
Nas reboot.
Page blank.

Thx for helping

### Logs

```markdown
Error: Node.js global modules rebuild required. See log errors above.
    at main (/volume1/@appstore/homebridge/app/lib/node_modules/homebridge-config-ui-x/dist/main.js:29754:19)
    at 1808 (/volume1/@appstore/homebridge/app/lib/node_modules/homebridge-config-ui-x/dist/main.js:29806:1)
    at __webpack_require__ (/volume1/@appstore/homebridge/app/lib/node_modules/homebridge-config-ui-x/dist/main.js:30138:42)
    at /volume1/@appstore/homebridge/app/lib/node_modules/homebridge-config-ui-x/dist/main.js:30166:1
    at /volume1/@appstore/homebridge/app/lib/node_modules/homebridge-config-ui-x/dist/main.js:30272:3
    at Object.<anonymous> (/volume1/@appstore/homebridge/app/lib/node_modules/homebridge-config-ui-x/dist/main.js:30277:12)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12
```

### Configuration

```json
{
    "bridge": {
        "name": "Homebridge 4B5A",
        "username": "0E:1E:6B:8B:4B:5A",
        "port": 51927,
        "pin": "447-53-642",
        "advertiser": "avahi"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "name": "Camera FFmpeg",
            "cameras": [
                {
                    "name": "Romy",
                    "motion": false,
                    "switches": false,
                    "motionTimeout": 15,
                    "unbridge": true,
                    "videoConfig": {
                        "source": "-rtsp_transport tcp -re -i rtsp://admin:VSPSVL@192.168.1.30:554/channel0",
                        "audio": false,
                        "debug": false
                    },
                    "mqtt": {
                        "motionTopic": "home/camera",
                        "motionMessage": "ON",
                        "motionResetTopic": "home/camera",
                        "motionResetMessage": "OFF"
                    }
                }
            ],
            "_bridge": {
                "username": "0E:58:5B:55:43:16",
                "port": 47483
            },
            "platform": "Camera-ffmpeg"
        },
        {
            "hostname": "mediation.tydom.com",
            "username": "001A25062368",
            "password": "$MrK,W2OnH0u^AW",
            "debug": true,
            "platform": "Tydom",
            "_bridge": {
                "username": "0E:51:D5:06:C1:81",
                "port": 37522
            }
        }
    ],
    "disabledPlugins": [
"config.json" 59L, 1735B
```

### Environment

- OS: DSM7
- Software:
- Node: v16.17.0
- nmp : 8.15.0
Homebridge Version : 3.0.17

### Process Supervisor

hb-service

**Comment by NorthernMan54** [comment] 2023-10-30 16:12
I believe this is a duplicate of https://github.com/homebridge/homebridge-syno-spk/issues/138

**Comment by DaGreenX** [comment] 2023-10-30 17:58
> I believe this is a duplicate of [homebridge/homebridge-syno-spk#138](https://github.com/homebridge/homebridge-syno-spk/issues/138)

Thx buddy. doesn't works for me. how can I restore previous version of Homebridge ?

**Comment by WillFulmer** [comment] 2023-11-30 02:00
@DaGreenX - having the exact same issue as you and have been trying to upgrade/downgrade uninstall and reinstall - with no luck.

Have you had success in fixing this?

Same error log:
[11/29/2023, 8:58:55 PM] Got SIGTERM, shutting down Homebridge...
[11/29/2023, 8:59:01 PM] [HB Supervisor] OS: Linux 3.10.108 arm
[11/29/2023, 8:59:01 PM] [HB Supervisor] Node.js v18.15.0 /volume1/@appstore/Node.js_v18/usr/local/bin/node
[11/29/2023, 8:59:01 PM] [HB Supervisor] Homebridge Path: /volume1/homebridge/node_modules/homebridge/bin/homebridge
[11/29/2023, 8:59:01 PM] [HB Supervisor] UI Path: /var/packages/homebridge/target/app/lib/node_modules/homebridge-config-ui-x/dist/bin/standalone.js
prebuild-file-path: /volume1/@appstore/homebridge/app/lib/node_modules/homebridge-config-ui-x/node_modules/@homebridge/node-pty-prebuilt-multiarch/prebuilds/linux-arm/node.abi108.node
innerError Error: /volume1/@appstore/homebridge/app/lib/node_modules/homebridge-config-ui-x/node_modules/@homebridge/node-pty-prebuilt-multiarch/build/Release/pty.node: internal error
    at Module._extensions..node (node:internal/modules/cjs/loader:1338:18)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/volume1/@appstore/homebridge/app/lib/node_modules/homebridge-config-ui-x/node_modules/@homebridge/node-pty-prebuilt-multiarch/lib/prebuild-loader.js:10:15)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12) {
  code: 'ERR_DLOPEN_FAILED'
}
[11/29/2023, 8:59:02 PM] [Homebridge UI] Error: /lib/libc.so.6: version `GLIBC_2.28' not found (required by /volume1/@appstore/homebridge/app/lib/node_modules/homebridge-config-ui-x/node_modules/@homebridge/node-pty-prebuilt-multiarch/prebuilds/linux-arm/node.abi108.node)
[11/29/2023, 8:59:02 PM] [Homebridge UI] [node-pty] Node.js v18.15.0
[11/29/2023, 8:59:02 PM] [Homebridge UI] [node-pty] Failed to load node-pty module
[11/29/2023, 8:59:02 PM] [Homebridge UI] [node-pty] This could be because the installation of this plugin did not complete successfully or you may have recently upgraded Node.js to a new major version.
[11/29/2023, 8:59:02 PM] [Homebridge UI] [node-pty] Follow the steps below to resolve this issue.
[11/29/2023, 8:59:02 PM] [Homebridge UI] [node-pty] Trying to rebuild automatically...
[11/29/2023, 8:59:02 PM] [Homebridge UI] [node-pty] Path: /volume1/@appstore/homebridge/app/lib/node_modules/homebridge-config-ui-x/node_modules/@homebridge/node-pty-prebuilt-multiarch
[11/29/2023, 8:59:19 PM] [Homebridge UI] [node-pty] Module rebuilt successfully (maybe) - if you are still encountering errors follow the steps below.
[11/29/2023, 8:59:19 PM] [Homebridge UI] [node-pty] From the terminal run this command to rebuild npm modules:

[11/29/2023, 8:59:19 PM] [Homebridge UI] sudo hb-service rebuild

[11/29/2023, 8:59:19 PM] [HB Supervisor] ERROR: The user interface threw an unhandled error
Error: Node.js global modules rebuild required. See log errors above.
    at main (/volume1/@appstore/homebridge/app/lib/node_modules/homebridge-config-ui-x/dist/main.js:31752:19)
    at 1808 (/volume1/@appstore/homebridge/app/lib/node_modules/homebridge-config-ui-x/dist/main.js:31774:1)
    at __webpack_require__ (/volume1/@appstore/homebridge/app/lib/node_modules/homebridge-config-ui-x/dist/main.js:32106:42)
    at /volume1/@appstore/homebridge/app/lib/node_modules/homebridge-config-ui-x/dist/main.js:32134:1
    at /volume1/@appstore/homebridge/app/lib/node_modules/homebridge-config-ui-x/dist/main.js:32240:3
    at Object.<anonymous> (/volume1/@appstore/homebridge/app/lib/node_modules/homebridge-config-ui-x/dist/main.js:32245:12)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
[11/29/2023, 8:59:19 PM] [HB Supervisor] Starting Homebridge with extra flags: -I -P /volume1/homebridge/node_modules --strict-plugin-resolution
[11/29/2023, 8:59:19 PM] [HB Supervisor] Started Homebridge v1.7.0 with PID: 1295
[11/29/2023, 8:59:22 PM] Loaded config.json with 0 accessories and 1 platforms.
[11/29/2023, 8:59:22 PM] Loaded 0 cached accessories from cachedAccessories.
[11/29/2023, 8:59:22 PM] ---
[11/29/2023, 8:59:22 PM] No plugins found.
[11/29/2023, 8:59:22 PM] Loading 1 platforms...
Setup Payload:
X-HM://0024EAUIOME04
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:

    ┌────────────┐
    │ 560-47-360 │
    └────────────┘

[11/29/2023, 8:59:22 PM] Error: listen EADDRINUSE: address already in use :::51566
    at Server.setupListenHandle [as _listen2] (node:net:1740:16)
    at listenInCluster (node:net:1788:12)
    at Server.listen (node:net:1876:7)
    at EventedHTTPServer.listen (/volume1/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/eventedhttp.ts:164:20)
    at HAPServer.listen (/volume1/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/HAPServer.ts:377:21)
    at Bridge.<anonymous> (/volume1/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1365:18)
    at step (/volume1/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:195:27)
    at Object.next (/volume1/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:176:57)
    at fulfilled (/volume1/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:166:62)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[11/29/2023, 8:59:22 PM] Got SIGTERM, shutting down Homebridge...

**Closed as completed** 2024-01-04 16:00 UTC
Labels: question
