### ISSUE TITLE
3.0.20 won't start web interface after updating from previous version with node version updated

### ISSUE THREAD

**Issue by Cookieko** [oznu/homebridge-syno-spk#140] opened 2023-12-31 15:07 UTC
### Raspberry Pi Model

Other (specify in description)

### Describe The Bug

**Analysis**
Web interface do not start.

**Expected Behavior**
Web interface should start

**Steps To Reproduce**
In DSM 7.1.1-42962 Update 5 in an Synology DS216j nas, with the version of Node installed in the package (18.15.0-0008), update of Homebridge to 3.0.20, the web user interface does no longer work, I get the connextion restarted browser error each time: No access to 192.xxx.xxx.xx:8581
I tried to reinstall both Homebridge and Node -> same issue
I tried to sudo hb-service rebuild, sudo npm install -g npm@10.2.1, sudo reboot -> same issue

Any ideas? Thanks in advance!

### Logs

```text
[37m[12/31/2023, 2:51:20 PM][0m [36m[HB Supervisor][0m Creating default config.json: /volume2/homebridge/config.json
[37m[12/31/2023, 2:51:20 PM][0m [36m[HB Supervisor][0m OS: Linux 3.10.108 arm
[37m[12/31/2023, 2:51:20 PM][0m [36m[HB Supervisor][0m Node.js v18.15.0 /volume2/@appstore/Node.js_v18/usr/local/bin/node
[37m[12/31/2023, 2:51:20 PM][0m [36m[HB Supervisor][0m Homebridge Path: /volume2/homebridge/node_modules/homebridge/bin/homebridge
[37m[12/31/2023, 2:51:20 PM][0m [36m[HB Supervisor][0m UI Path: /var/packages/homebridge/target/app/lib/node_modules/homebridge-config-ui-x/dist/bin/standalone.js
prebuild-file-path: /volume2/@appstore/homebridge/app/lib/node_modules/homebridge-config-ui-x/node_modules/@homebridge/node-pty-prebuilt-multiarch/prebuilds/linux-arm/node.abi108.node
innerError Error: Cannot find module '../build/Release/pty.node'
Require stack:
- /volume2/@appstore/homebridge/app/lib/node_modules/homebridge-config-ui-x/node_modules/@homebridge/node-pty-prebuilt-multiarch/lib/prebuild-loader.js
- /volume2/@appstore/homebridge/app/lib/node_modules/homebridge-config-ui-x/node_modules/@homebridge/node-pty-prebuilt-multiarch/lib/unixTerminal.js
- /volume2/@appstore/homebridge/app/lib/node_modules/homebridge-config-ui-x/node_modules/@homebridge/node-pty-prebuilt-multiarch/lib/index.js
- /volume2/@appstore/homebridge/app/lib/node_modules/homebridge-config-ui-x/dist/main.js
- /volume2/@appstore/homebridge/app/lib/node_modules/homebridge-config-ui-x/dist/bin/hb-service.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
    at Module._load (node:internal/modules/cjs/loader:920:27)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/volume2/@appstore/homebridge/app/lib/node_modules/homebridge-config-ui-x/node_modules/@homebridge/node-pty-prebuilt-multiarch/lib/prebuild-loader.js:10:15)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/volume2/@appstore/homebridge/app/lib/node_modules/homebridge-config-ui-x/node_modules/@homebridge/node-pty-prebuilt-multiarch/lib/prebuild-loader.js',
    '/volume2/@appstore/homebridge/app/lib/node_modules/homebridge-config-ui-x/node_modules/@homebridge/node-pty-prebuilt-multiarch/lib/unixTerminal.js',
    '/volume2/@appstore/homebridge/app/lib/node_modules/homebridge-config-ui-x/node_modules/@homebridge/node-pty-prebuilt-multiarch/lib/index.js',
    '/volume2/@appstore/homebridge/app/lib/node_modules/homebridge-config-ui-x/dist/main.js',
    '/volume2/@appstore/homebridge/app/lib/node_modules/homebridge-config-ui-x/dist/bin/hb-service.js'
  ]
}
[0;37m[12/31/2023, 2:51:23 PM] [0m[0;36m[Homebridge UI][0m [0;31mError: /lib/libc.so.6: version `GLIBC_2.28' not found (required by /volume2/@appstore/homebridge/app/lib/node_modules/homebridge-config-ui-x/node_modules/@homebridge/node-pty-prebuilt-multiarch/prebuilds/linux-arm/node.abi108.node)[0m
[0;37m[12/31/2023, 2:51:23 PM] [0m[0;36m[Homebridge UI][0m [0;31m[node-pty] Node.js v18.15.0[0m
[0;37m[12/31/2023, 2:51:23 PM] [0m[0;36m[Homebridge UI][0m [0;31m[node-pty] Failed to load node-pty module[0m
[0;37m[12/31/2023, 2:51:23 PM] [0m[0;36m[Homebridge UI][0m [0;31m[node-pty] This could be because the installation of this plugin did not complete successfully or you may have recently upgraded Node.js to a new major version.[0m
[0;37m[12/31/2023, 2:51:23 PM] [0m[0;36m[Homebridge UI][0m [0;31m[node-pty] Follow the steps below to resolve this issue.[0m
[0;37m[12/31/2023, 2:51:23 PM] [0m[0;36m[Homebridge UI][0m [0;33m[node-pty] Trying to rebuild automatically...[0m
[0;37m[12/31/2023, 2:51:23 PM] [0m[0;36m[Homebridge UI][0m [0;33m[node-pty] Path: /volume2/@appstore/homebridge/app/lib/node_modules/homebridge-config-ui-x/node_modules/@homebridge/node-pty-prebuilt-multiarch[0m
[0;37m[12/31/2023, 2:51:37 PM] [0m[0;36m[Homebridge UI][0m [0;31m[node-pty] Failed to rebuild npm modules automatically. Manual operation is now required.[0m
[0;37m[12/31/2023, 2:51:37 PM] [0m[0;36m[Homebridge UI][0m [0;33m[node-pty] From the terminal run this command to rebuild npm modules:
[0m
[0;37m[12/31/2023, 2:51:37 PM] [0m[0;36m[Homebridge UI][0m [0;33msudo hb-service rebuild
[0m
[37m[12/31/2023, 2:51:37 PM][0m [36m[HB Supervisor][0m ERROR: The user interface threw an unhandled error
Error: Node.js global modules rebuild required. See log errors above.
    at main (/volume2/@appstore/homebridge/app/lib/node_modules/homebridge-config-ui-x/dist/main.js:31752:19)
    at 1808 (/volume2/@appstore/homebridge/app/lib/node_modules/homebridge-config-ui-x/dist/main.js:31774:1)
    at __webpack_require__ (/volume2/@appstore/homebridge/app/lib/node_modules/homebridge-config-ui-x/dist/main.js:32106:42)
    at /volume2/@appstore/homebridge/app/lib/node_modules/homebridge-config-ui-x/dist/main.js:32134:1
    at /volume2/@appstore/homebridge/app/lib/node_modules/homebridge-config-ui-x/dist/main.js:32240:3
    at Object.<anonymous> (/volume2/@appstore/homebridge/app/lib/node_modules/homebridge-config-ui-x/dist/main.js:32245:12)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
[37m[12/31/2023, 2:51:37 PM][0m [36m[HB Supervisor][0m Starting Homebridge with extra flags: -I -P /volume2/homebridge/node_modules --strict-plugin-resolution
[37m[12/31/2023, 2:51:37 PM][0m [36m[HB Supervisor][0m Started Homebridge v1.7.0 with PID: 4375
[37m[12/31/2023, 2:51:40 PM] [39mLoaded config.json with 0 accessories and 1 platforms.
[37m[12/31/2023, 2:51:40 PM] [39m---
[37m[12/31/2023, 2:51:40 PM] [39m[33mNo plugins found.[39m
[37m[12/31/2023, 2:51:40 PM] [39mLoading 1 platforms...
```

**Comment by NorthernMan54** [comment] 2023-12-31 15:32
Duplicate of #138

**Closed as completed by NorthernMan54** 2023-12-31 15:32 UTC
Labels: bug

**Comment by Cookieko** [comment] 2023-12-31 18:13
I realy tried to study #138 in detail before... Now I found the hint: Manually updating DSM-Software. Cheers...
